name: mapalab-caddy

services:
  caddy:
    image: caddy:2-alpine
    container_name: mapalab-caddy
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    env_file:
      - .env
    networks:
      - mapalab-network
    restart: unless-stopped

volumes:
  caddy_data:
    name: mapalab-caddy-data
  caddy_config:
    name: mapalab-caddy-config

networks:
  mapalab-network:
    name: ${NETWORK_NAME:-mapalab-network}
    external: true
