export const EXPORT_DIMENSIONS = {
    TOTAL_WIDTH: 2550,
    TOTAL_HEIGHT: 1700,
    SIDE_PANEL_WIDTH: 543,
    SIDE_PANEL_CONTENT_WIDTH: 516,
    SIDE_PANEL_MARGIN_RIGHT: 27,
    MAP_WIDTH: 2007,
    MAP_HEIGHT: 1700,
    LABEL_MARGIN_X: 27,
    LABEL_MARGIN_Y: 23,
    LABEL_OFFSET: 20,
    FRAME_BORDER_WIDTH: 1,
    FRAME_COLOR: '#707070',
    NUM_DIVISIONS_X: 5,
    NUM_DIVISIONS_Y: 4
};
