name: mapalab

services:
  nginx:
    build:
      context: .
    ports:
      - '${NGINX_PORT:-3006}:80'
    volumes:
      - ../frontend/dist:/usr/share/nginx/html:ro
    networks:
      - mapalab-network
    restart: unless-stopped

networks:
  mapalab-network:
    name: ${NETWORK_NAME:-mapalab-network}
    external: true
