name: mapalab

services:
  nginx:
    build:
      context: .
    env_file:
      - .env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../frontend/dist:/usr/share/nginx/html:ro
      - ${SSL_VOLUME_PATH}
    environment:
      SSL_MODE: ${SSL_MODE:-true}
      SSL_CERTIFICATE: ${SSL_CERTIFICATE:-/etc/nginx/certs/fullchain.pem}
      SSL_CERTIFICATE_KEY: ${SSL_CERTIFICATE_KEY:-/etc/nginx/certs/privkey.pem}
      APP_DOMAIN: ${APP_DOMAIN:-localhost}
      BACKEND_HOST: ${BACKEND_HOST:-backend:8000}
      GEOSERVER_HOST: ${GEOSERVER_HOST:-localhost}
      ALLOWED_IP: ${ALLOWED_IP:-127.0.0.1}
    networks:
      - mapalab-network
    restart: unless-stopped

networks:
  mapalab-network:
    name: ${NETWORK_NAME:-mapalab-network}
    external: true
